[build]
  # Build will execute inside this subdirectory
  base = "frontend"
  # Output directory relative to 'base'
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  # IMPORTANT: Set this to your deployed backend (FastAPI) base URL. You can also override in Netlify UI.
  # Example if backend deployed on Render / Railway / Fly:
  # VITE_API_BASE = "https://podcast-api.onrender.com"
  VITE_API_BASE = "https://YOUR-BACKEND-URL"

# Optionally you can override only for production context:
# [context.production.environment]
#   VITE_API_BASE = "https://your-prod-backend.example.com"

# Redirect all SPA routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
